image: registry-jf.sensedeal.wiki:9443/library/ci-ubuntu:20.04
variables:
  PIP_CACHE_DIR: "/data/.cache/pip"
  CI_REGISTRY_IMAGE: registry-jf.sensedeal.wiki:9443/ie/sdai-pdfs-ocr-torch-gpu 
  CI_REGISTRY: registry-jf.sensedeal.wiki:9443
  GIT_SUBMODULE_STRATEGY: recursive
  CACHE_TAG: 1.2.4
docker-build:
  timeout: 3 hours 30 minutes
  image:
    name: docker:20.10.16
  stage: build
  services:
  - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: ''
    DOCKER_BUILDKIT: 1
  before_script:
  - export VERSION=${CI_COMMIT_TAG:-$(echo $CI_COMMIT_BRANCH | sed 's/[^a-zA-Z0-9]/-/g')-$(date
    +%y%m%d)-$CI_COMMIT_SHORT_SHA}
  - echo "VERSION:" "$VERSION"
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    "$CI_REGISTRY"
  script:
  - docker build -t "$CI_REGISTRY_IMAGE:$VERSION" .
  - docker push "$CI_REGISTRY_IMAGE:$VERSION"
  - echo "Docker image pushed:" "$CI_REGISTRY_IMAGE:$VERSION"
  when: manual
