###############
##
####

GPU: [0, 1, 2, 3]

VERBOSE: True

MODEL:
  MODE: 'SuperResolution'
  SESSION: 'MPRNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 12
  NUM_EPOCHS: 2500
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 10
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 128
  TRAIN_DIR: '/workspace/JuneLi/bbtv/SensedealImgAlg/DATASETS/RES/SuperResolution/v0/train'       # path to training data
  VAL_DIR: '/workspace/JuneLi/bbtv/SensedealImgAlg/DATASETS/RES/SuperResolution/v0/val' # path to validation data
  SAVE_DIR: '/workspace/JuneLi/bbtv/SensedealImgAlg/MODEL/RES/MPRNet/MPRNetv0/SuperResolution/20211126/runs/checkpoints'           # path to save models and images
  # SAVE_IMAGES: False
