GPU: [0, 1, 2, 3]

VERBOSE: True

MODEL:
  MODE: 'DeSeal'
  SESSION: 'MPRNet'

TEST:
  BATCH_SIZE: 16
  RESUME: '/workspace/JuneLi/bbtv/SensedealImgAlg/MODEL/RES/MPRNet/MPRNetv0/DeSeal/20211122/best.pt'
  TEST_PS: 128
  TEST_DIR: '/workspace/JuneLi/bbtv/SensedealImgAlg/DATASETS/RES/DeSeal/v1/test' # path to validation data
